### ISSUE TITLE
Empty or no response from rtstatus after increasing number of backends through certain level

### ISSUE THREAD

**Issue by anordby** [varnish/libvmod-rtstatus#8]
After increasing from 16 to 18 backends (8 to 9 probes), rtstatus starts returning either:
1) Empty response:

`$ lynx -dump http://no000010sapit0.moller.local/rtstatus                             * [1]GITHUB
     * [2]JSON

VARNISH STATUS

   Backends Num Req Conn Unhealthy Busy Fail Reuse Toolate Recycle Retry

   Backend name Health Req KB/s Requests Resp KB/s Responses Pipe hdr Pipe
   out Pipe in
   [3]Show detailed counters
   Description Name Value
     __________________________________________________________________

   ©Copyright 2015 Varnish Software AS

References

   1. https://github.com/arianna-aondio/libvmod-rtstatus
   2. http://no000010sapit0.moller.local/rtstatus.json
   3. javascript:openSpoiler('spoil')`

2) No response:

`$ curl -I http://no000010sapit0.moller.local/rtstatus.json
curl: (52) Empty reply from server`

**Comment by aondio** [comment]
I'll try to reproduce and get back to you ASAP.
Thank you for reporting.

Arianna Aondio
Software Developer | Varnish Software AS
Mobile: +47 980 62 02 619

**Comment by anordby** [comment]
After increasing workspace_client from the default of 64 KB to 256 K,  it works OK to check the status of 24 backends using 12 different probes, with 12 (random) directors. So this works OK for me now after discussing it with Espen.

**Comment by aondio** [comment]
Thank you for the update.
I'll look into this anyway as soon as I can :)

**Comment by aondio** [comment]
Hi anordby,
just a quick update, I'm working on this VMOD, I've pushed a change that should fix the problem related to the number of backends. So far I've been testing it with 44 backends and works fine.
Feel free to test it if you feel like it.

**Comment by anordby** [comment]
How is that different than to simply increase workspace_client? Any less memory usage? Increasing workspace_client already solved the problems for me.

**Comment by aondio** [comment]
Hi Anders,
before commit ac3288e481a814e4d9bea1197a549ec3c76899c6 the VMOD used to relay on the client_workspace for any kind of operations that required some memory allocation. In this particular case the client_workspace was used for allocating the string containing the Json, which, as you have experienced, could also require quite a lot of space.
After the commit, the VMOD uses ctx->req->synth_body which is the string that is used wen we fall in vcl_synth to generate synthetic objects. This synth_body doesn't use the client_workspace, but it is allocated as part of the ctx struct.

**Comment by obliadp** [comment]
Hi,

this problem still exists in VCP4.0. Any chance of including the fix there?

I have 86 directors atm. and seem to need a workspace_session of 512kib.

**Comment by aondio** [comment]
Hi obliadp,
you are using the branch 4.0,correct?
If so, the branch 4.0 should be fixed after the commit ac3288e.

**Comment by obliadp** [comment]
Yes, but we use Varnish Plus, and the modules included in prebuilt packages
is older than this commit, as far as I can see. I'm on EL6.

**Comment by aondio** [comment]
Hi obliadp,
do you have the possibility to build it from source?

**Comment by obliadp** [comment]
Not really, but you can close this issue, I'll switch to IRC as the finer points of package management discussion doesn't need to happen here :-) Thank you for your quick response.
